# Generated by Django 2.1.7 on 2019-03-27 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name_plural': '部门表',
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=32)),
                ('UD', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='status.Department')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'db_table': 'User',
            },
        ),
    ]
