# Generated by Django 2.1.7 on 2019-03-27 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20190327_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='UD',
        ),
        migrations.AddField(
            model_name='user',
            name='UD',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='status.Department'),
            preserve_default=False,
        ),
    ]
