# Generated by Django 2.1.7 on 2019-03-14 03:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('comments', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '内容表',
                'db_table': 'Content',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=32)),
                ('team_leader', models.CharField(max_length=32)),
                ('status', models.IntegerField(choices=[(1, '初期'), (2, '中期'), (3, '后期'), (4, '完成')])),
            ],
            options={
                'verbose_name_plural': '博客表',
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存时间')),
                ('mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('PT', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Project')),
            ],
            options={
                'verbose_name_plural': '时间表',
                'db_table': 'Time',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='PC',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Project'),
        ),
    ]
