# Generated by Django 2.1.7 on 2019-03-14 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_project_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='add_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='保存时间'),
        ),
        migrations.AlterField(
            model_name='time',
            name='mod_time',
            field=models.DateField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
