# Generated by Django 2.1.7 on 2019-03-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190314_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='add_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='time',
            name='mod_time',
            field=models.DateTimeField(),
        ),
    ]
