# Generated by Django 2.1.7 on 2019-03-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190314_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='add_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='time',
            name='mod_time',
            field=models.DateField(),
        ),
    ]
