# Generated by Django 2.1.7 on 2019-03-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_time_mod_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='add_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
